### ISSUE TITLE
got an error "convalution havn't activate linear"

### ISSUE THREAD

**Issue by hahaheihei09** [guhuozhengling/deepsort_yolov4#3]
Hi,

It seems something is wrong here to run the code. Do you have any suggestions on this?

"convalution havn't activate linear
convalution havn't activate linear
convalution havn't activate linear
Loading weights from ckpt.t7... Done!
Unexpected element. Expected: idx1. Got: �mov.
Failed to parse avi: index was not found
utils/utils.py:14: RuntimeWarning: overflow encountered in exp
  return 1.0 / (np.exp(-x) + 1.)
time: 0.487s, fps: 2.054
time: 0.462s, fps: 2.164
(<type 'exceptions.IndexError'>, IndexError('index 707 is out of bounds for axis 0 with size 3',), <traceback object at 0x7f9770bf15a8>)
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    vdo_trk.run()
  File "main.py", line 85, in run
    ori_im = draw_boxes(ori_im, bbox_xyxy, identities)
  File "utils/draw.py", line 22, in draw_boxes
    id = int(identities[i]) if identities is not None else 0
IndexError: index 707 is out of bounds for axis 0 with size 3
"

**Comment by guhuozhengling** [comment]
Maybe there is something with your test video?Try test more video?

**Comment by hahaheihei09** [comment]
Thanks for your reply. I used your video demo2.avi and got this error. I tried my own video and got similar error as follows. Do you think this is a python version problem? I am using python 2.7, cuda9.0, torch1.1.0
convalution havn't activate linear
convalution havn't activate linear
convalution havn't activate linear
Loading weights from ckpt.t7... Done!
utils/utils.py:14: RuntimeWarning: overflow encountered in exp
  return 1.0 / (np.exp(-x) + 1.)
(<type 'exceptions.IndexError'>, IndexError('too many indices for tensor of dimension 1',), <traceback object at 0x7fa1eee88248>)
Traceback (most recent call last):
  File "main.py", line 116, in <module>
    vdo_trk.run()
  File "main.py", line 64, in run
    bbox = boxes[:, :4]
IndexError: too many indices for tensor of dimension 1

**Comment by guhuozhengling** [comment]
Oh,I haven't tested python2 yet.I am using python 3.7,cuda version is not important, and pytorch>=1.0 is ok.
