### ISSUE TITLE
code is not working after running main.py

### ISSUE THREAD

**Issue by akashAD98** [guhuozhengling/deepsort_yolov4#5]
i changed all paths & updated .yml file, I'm only getting warings & nothing .

(deep_sort_pytorch-master_new) G:\pytorch_deepsort_git\deepsort_yolov4-2new>python main.py video/test.mp4
G:\pytorch_deepsort_git\deepsort_yolov4-2new\utils\utils.py:567: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsa
fe. Please read https://msg.pyyaml.org/load for full details.
  self.update(yaml.load(fo.read()))
Traceback (most recent call last):
  File "main.py", line 117, in <module>
    with VideoTracker(cfg, args) as vdo_trk:
  File "main.py", line 16, in __init__
    raise UserWarning("Running in cpu mode!")
UserWarning: Running in cpu mode!

i got this warning & process is finished

**Comment by akashAD98** [comment]
its worked  fine when i used cuda
